[package]
name = "dvb-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.7"
prost = "0.10"
tokio = { version = "1.18", features = ["macros", "rt-multi-thread"] }

tungstenite = "0.17.2"

serde = { version = "*", features = ["derive"] }
serde_json = "*"

actix-web = "*"
actix-rt = "*"
actix-multipart = "0.4.0"
actix-cors = "0.6.0-beta.4"

[build-dependencies]
tonic-build = "0.7"
